name: VentFit Build and Test CI (Android)

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Run Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    # Setup java environment to build android app
    - uses: actions/checkout@v3
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle
    
    # Setup flutter environment
    - uses: actions/checkout@v3
    - name: Setup Flutter env
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.7'
        channel: 'stable'
        cache: true

    - name: Clean project
      run: flutter clean

    - name: Get dependencies
      run: flutter pub get

    - name: Checking formatting issues
      run: flutter format --set-exit-if-changed .
    
    - name: Analyze dart code
      run: flutter analyze .
    
    - name: Run test
      run: flutter test
    
    - name: Build apk
      run: flutter build apk --debug --split--per-abi
